export const communities = [
  { id: 'ESNC', name: 'Navarra' },
  { id: 'ESPV', name: 'País Vasco' },
  { id: 'ESRI', name: 'La Rioja' },
  { id: 'ESCT', name: 'Cataluña' },
  { id: 'ESAR', name: 'Aragón' },
  { id: 'ESEX', name: 'Extremadura' },
  { id: 'ESGA', name: 'Galicia' },
  { id: 'ESCL', name: 'Castilla y León' },
  { id: 'ESVC', name: 'Comunidad Valenciana' },
  { id: 'ESMC', name: 'Región de Murcia' },
  { id: 'ESAN', name: 'Andalucía' },
  { id: 'ESAS', name: 'Asturias' },
  { id: 'ESCB', name: 'Cantabria' },
  { id: 'ESCN', name: 'Islas Canarias' },
  { id: 'ESIB', name: 'Islas Baleares' },
  { id: 'ESCM', name: 'Castilla-La Mancha' },
  { id: 'ESMD', name: 'Comunidad de Madrid' },
  { id: 'ESCE', name: 'Ceuta' },
  { id: 'ESML', name: 'Melilla' }
];

export const provinces = [
  { id: 'ESCE', name: 'Ceuta', capital: 'Ceuta' },
  { id: 'ESML', name: 'Melilla', capital: 'Melilla' },
  { id: 'ESNA', name: 'Navarra', capital: 'Pamplona' },
  { id: 'ESSS', name: 'Gipuzkoa', capital: 'San Sebastián' },
  { id: 'ESHU', name: 'Huesca', capital: 'Huesca' },
  { id: 'ESBI', name: 'Bizkaia', capital: 'Bilbao' },
  { id: 'ESZ', name: 'Zaragoza', capital: 'Zaragoza' },
  { id: 'ESLO', name: 'La Rioja', capital: 'Logroño' },
  { id: 'ESVI', name: 'Álava', capital: 'Vitoria-Gasteiz' },
  { id: 'ESSO', name: 'Soria', capital: 'Soria' },
  { id: 'ESBU', name: 'Burgos', capital: 'Burgos' },
  { id: 'ESL', name: 'Lérida', capital: 'Lérida' },
  { id: 'EST', name: 'Tarragona', capital: 'Tarragona' },
  { id: 'ESTE', name: 'Teruel', capital: 'Teruel' },
  { id: 'ESGI', name: 'Gerona', capital: 'Gerona' },
  { id: 'ESB', name: 'Barcelona', capital: 'Barcelona' },
  { id: 'ESBA', name: 'Badajoz', capital: 'Badajoz' },
  { id: 'ESCC', name: 'Cáceres', capital: 'Cáceres' },
  { id: 'ESH', name: 'Huelva', capital: 'Huelva' },
  { id: 'ESSE', name: 'Sevilla', capital: 'Sevilla' },
  { id: 'ESTO', name: 'Toledo', capital: 'Toledo' },
  { id: 'ESCR', name: 'Ciudad Real', capital: 'Ciudad Real' },
  { id: 'ESCO', name: 'Córdoba', capital: 'Córdoba' },
  { id: 'ESCA', name: 'Cádiz', capital: 'Cádiz' },
  { id: 'ESMA', name: 'Málaga', capital: 'Málaga' },
  { id: 'ESOR', name: 'Orense', capital: 'Orense' },
  { id: 'ESZA', name: 'Zamora', capital: 'Zamora' },
  { id: 'ESPO', name: 'Pontevedra', capital: 'Pontevedra' },
  { id: 'ESC', name: 'La Coruña', capital: 'La Coruña' },
  { id: 'ESLU', name: 'Lugo', capital: 'Lugo' },
  { id: 'ESLE', name: 'León', capital: 'León' },
  { id: 'ESSA', name: 'Salamanca', capital: 'Salamanca' },
  { id: 'ESAV', name: 'Ávila', capital: 'Ávila' },
  { id: 'ESVA', name: 'Valladolid', capital: 'Valladolid' },
  { id: 'ESCS', name: 'Castellón', capital: 'Castellón de la Plana' },
  { id: 'ESV', name: 'Valencia', capital: 'Valencia' },
  { id: 'ESA', name: 'Alicante', capital: 'Alicante' },
  { id: 'ESMU', name: 'Murcia', capital: 'Murcia' },
  { id: 'ESAB', name: 'Albacete', capital: 'Albacete' },
  { id: 'ESCU', name: 'Cuenca', capital: 'Cuenca' },
  { id: 'ESAL', name: 'Almería', capital: 'Almería' },
  { id: 'ESGR', name: 'Granada', capital: 'Granada' },
  { id: 'ESJ', name: 'Jaén', capital: 'Jaén' },
  { id: 'ESO', name: 'Asturias', capital: 'Oviedo' },
  { id: 'ESS', name: 'Cantabria', capital: 'Santander' },
  { id: 'ESP', name: 'Palencia', capital: 'Palencia' },
  { id: 'ESTF', name: 'Santa Cruz de Tenerife', capital: 'Santa Cruz de Tenerife' },
  { id: 'ESGC', name: 'Las Palmas', capital: 'Las Palmas de Gran Canaria' },
  { id: 'ESPM', name: 'Baleares', capital: 'Palma de Mallorca' },
  { id: 'ESGU', name: 'Guadalajara', capital: 'Guadalajara' },
  { id: 'ESM', name: 'Madrid', capital: 'Madrid' },
  { id: 'ESSG', name: 'Segovia', capital: 'Segovia' }
];
