export const CONTINENTS = [
    { id: "europe", label: "Europa" },
    { id: "asia", label: "Asia" },
    { id: "africa", label: "Africa" },
    { id: "north-america", label: "America del Norte" },
    { id: "south-america", label: "America del Sur" },
    { id: "oceania", label: "Oceania" },
] as const;

export type ContinentId = (typeof CONTINENTS)[number]["id"];

export interface Country {
    code: string;
    name: string;
    continent: ContinentId;
    tier: 1 | 2 | 3 | 4;
    flagFamily: string;
    aliases?: string[];
}

export const countries: Country[] = [
    { code: "es", name: "Espana", continent: "europe", tier: 1, flagFamily: "horizontal-red-yellow", aliases: ["spain"] },
    { code: "fr", name: "Francia", continent: "europe", tier: 1, flagFamily: "vertical-tricolor", aliases: ["france"] },
    { code: "it", name: "Italia", continent: "europe", tier: 1, flagFamily: "vertical-tricolor", aliases: ["italy"] },
    { code: "de", name: "Alemania", continent: "europe", tier: 1, flagFamily: "horizontal-tricolor", aliases: ["germany"] },
    { code: "pt", name: "Portugal", continent: "europe", tier: 1, flagFamily: "vertical-bicolor" },
    { code: "gb", name: "Reino Unido", continent: "europe", tier: 1, flagFamily: "union-jack", aliases: ["gran bretana", "inglaterra", "uk", "united kingdom"] },
    { code: "ie", name: "Irlanda", continent: "europe", tier: 2, flagFamily: "vertical-tricolor", aliases: ["ireland"] },
    { code: "nl", name: "Paises Bajos", continent: "europe", tier: 1, flagFamily: "horizontal-tricolor", aliases: ["holanda", "netherlands"] },
    { code: "be", name: "Belgica", continent: "europe", tier: 2, flagFamily: "vertical-tricolor" },
    { code: "ch", name: "Suiza", continent: "europe", tier: 1, flagFamily: "cross-red-white", aliases: ["switzerland"] },
    { code: "at", name: "Austria", continent: "europe", tier: 2, flagFamily: "horizontal-red-white" },
    { code: "dk", name: "Dinamarca", continent: "europe", tier: 2, flagFamily: "nordic-cross" },
    { code: "se", name: "Suecia", continent: "europe", tier: 1, flagFamily: "nordic-cross" },
    { code: "no", name: "Noruega", continent: "europe", tier: 1, flagFamily: "nordic-cross" },
    { code: "fi", name: "Finlandia", continent: "europe", tier: 2, flagFamily: "nordic-cross" },
    { code: "is", name: "Islandia", continent: "europe", tier: 3, flagFamily: "nordic-cross" },
    { code: "pl", name: "Polonia", continent: "europe", tier: 1, flagFamily: "horizontal-red-white" },
    { code: "cz", name: "Republica Checa", continent: "europe", tier: 2, flagFamily: "slavic-tricolor", aliases: ["chequia", "czechia"] },
    { code: "sk", name: "Eslovaquia", continent: "europe", tier: 3, flagFamily: "slavic-tricolor" },
    { code: "hu", name: "Hungria", continent: "europe", tier: 2, flagFamily: "horizontal-tricolor" },
    { code: "ro", name: "Rumania", continent: "europe", tier: 2, flagFamily: "vertical-tricolor" },
    { code: "bg", name: "Bulgaria", continent: "europe", tier: 2, flagFamily: "horizontal-tricolor" },
    { code: "gr", name: "Grecia", continent: "europe", tier: 1, flagFamily: "blue-white-cross" },
    { code: "ua", name: "Ucrania", continent: "europe", tier: 1, flagFamily: "horizontal-bicolor" },
    { code: "ru", name: "Rusia", continent: "europe", tier: 1, flagFamily: "slavic-tricolor" },
    { code: "hr", name: "Croacia", continent: "europe", tier: 3, flagFamily: "slavic-tricolor" },
    { code: "rs", name: "Serbia", continent: "europe", tier: 3, flagFamily: "slavic-tricolor" },
    { code: "si", name: "Eslovenia", continent: "europe", tier: 3, flagFamily: "slavic-tricolor" },
    { code: "al", name: "Albania", continent: "europe", tier: 3, flagFamily: "emblem-red" },
    { code: "lt", name: "Lituania", continent: "europe", tier: 3, flagFamily: "horizontal-tricolor" },
    { code: "lv", name: "Letonia", continent: "europe", tier: 3, flagFamily: "horizontal-red-white" },
    { code: "ee", name: "Estonia", continent: "europe", tier: 3, flagFamily: "horizontal-tricolor" },
    { code: "tr", name: "Turquia", continent: "asia", tier: 1, flagFamily: "crescent-red" },
    { code: "cn", name: "China", continent: "asia", tier: 1, flagFamily: "red-stars" },
    { code: "in", name: "India", continent: "asia", tier: 1, flagFamily: "horizontal-tricolor" },
    { code: "jp", name: "Japon", continent: "asia", tier: 1, flagFamily: "circle-white-red", aliases: ["japan"] },
    { code: "kr", name: "Corea del Sur", continent: "asia", tier: 1, flagFamily: "circle-white-red", aliases: ["surcorea"] },
    { code: "kp", name: "Corea del Norte", continent: "asia", tier: 2, flagFamily: "star-stripes", aliases: ["norcorea"] },
    { code: "id", name: "Indonesia", continent: "asia", tier: 1, flagFamily: "horizontal-red-white" },
    { code: "pk", name: "Pakistan", continent: "asia", tier: 1, flagFamily: "crescent-green" },
    { code: "bd", name: "Bangladesh", continent: "asia", tier: 1, flagFamily: "circle-green-red" },
    { code: "vn", name: "Vietnam", continent: "asia", tier: 1, flagFamily: "red-stars" },
    { code: "th", name: "Tailandia", continent: "asia", tier: 1, flagFamily: "horizontal-stripes" },
    { code: "ph", name: "Filipinas", continent: "asia", tier: 1, flagFamily: "triangle-sun" },
    { code: "my", name: "Malasia", continent: "asia", tier: 2, flagFamily: "stripes-canton" },
    { code: "sg", name: "Singapur", continent: "asia", tier: 2, flagFamily: "crescent-red" },
    { code: "sa", name: "Arabia Saudi", continent: "asia", tier: 1, flagFamily: "arab-green" },
    { code: "ae", name: "Emiratos Arabes Unidos", continent: "asia", tier: 2, flagFamily: "pan-arab" },
    { code: "qa", name: "Catar", continent: "asia", tier: 3, flagFamily: "serrated-red-white", aliases: ["qatar"] },
    { code: "kw", name: "Kuwait", continent: "asia", tier: 3, flagFamily: "pan-arab" },
    { code: "il", name: "Israel", continent: "asia", tier: 1, flagFamily: "blue-white-symbol" },
    { code: "ir", name: "Iran", continent: "asia", tier: 1, flagFamily: "horizontal-tricolor" },
    { code: "iq", name: "Irak", continent: "asia", tier: 2, flagFamily: "pan-arab", aliases: ["iraq"] },
    { code: "af", name: "Afganistan", continent: "asia", tier: 2, flagFamily: "vertical-tricolor" },
    { code: "np", name: "Nepal", continent: "asia", tier: 2, flagFamily: "unique-shape" },
    { code: "lk", name: "Sri Lanka", continent: "asia", tier: 2, flagFamily: "emblem-gold" },
    { code: "mm", name: "Myanmar", continent: "asia", tier: 3, flagFamily: "horizontal-star" },
    { code: "kh", name: "Camboya", continent: "asia", tier: 3, flagFamily: "horizontal-emblem" },
    { code: "la", name: "Laos", continent: "asia", tier: 3, flagFamily: "horizontal-circle" },
    { code: "mn", name: "Mongolia", continent: "asia", tier: 3, flagFamily: "vertical-tricolor" },
    { code: "kz", name: "Kazajistan", continent: "asia", tier: 2, flagFamily: "sky-symbol" },
    { code: "uz", name: "Uzbekistan", continent: "asia", tier: 3, flagFamily: "crescent-blue" },
    { code: "am", name: "Armenia", continent: "asia", tier: 3, flagFamily: "horizontal-tricolor" },
    { code: "az", name: "Azerbaiyan", continent: "asia", tier: 3, flagFamily: "crescent-blue" },
    { code: "eg", name: "Egipto", continent: "africa", tier: 1, flagFamily: "pan-arab" },
    { code: "ng", name: "Nigeria", continent: "africa", tier: 1, flagFamily: "vertical-green-white" },
    { code: "za", name: "Sudafrica", continent: "africa", tier: 1, flagFamily: "multicolor-y" },
    { code: "ke", name: "Kenia", continent: "africa", tier: 1, flagFamily: "pan-african" },
    { code: "et", name: "Etiopia", continent: "africa", tier: 1, flagFamily: "pan-african" },
    { code: "ma", name: "Marruecos", continent: "africa", tier: 1, flagFamily: "red-star" },
    { code: "dz", name: "Argelia", continent: "africa", tier: 1, flagFamily: "crescent-green" },
    { code: "tn", name: "Tunez", continent: "africa", tier: 2, flagFamily: "crescent-red" },
    { code: "gh", name: "Ghana", continent: "africa", tier: 1, flagFamily: "pan-african" },
    { code: "ci", name: "Costa de Marfil", continent: "africa", tier: 2, flagFamily: "vertical-tricolor" },
    { code: "sn", name: "Senegal", continent: "africa", tier: 2, flagFamily: "pan-african" },
    { code: "cm", name: "Camerun", continent: "africa", tier: 2, flagFamily: "pan-african" },
    { code: "tz", name: "Tanzania", continent: "africa", tier: 2, flagFamily: "diagonal" },
    { code: "ug", name: "Uganda", continent: "africa", tier: 2, flagFamily: "horizontal-emblem" },
    { code: "rw", name: "Ruanda", continent: "africa", tier: 3, flagFamily: "sun-blue" },
    { code: "ao", name: "Angola", continent: "africa", tier: 2, flagFamily: "emblem-red-black" },
    { code: "mz", name: "Mozambique", continent: "africa", tier: 2, flagFamily: "triangle-star" },
    { code: "mg", name: "Madagascar", continent: "africa", tier: 2, flagFamily: "horizontal-bicolor" },
    { code: "cd", name: "Republica Democratica del Congo", continent: "africa", tier: 2, flagFamily: "diagonal-star", aliases: ["congo kinshasa", "rd congo"] },
    { code: "sd", name: "Sudan", continent: "africa", tier: 2, flagFamily: "pan-arab" },
    { code: "ly", name: "Libia", continent: "africa", tier: 2, flagFamily: "crescent-red" },
    { code: "zw", name: "Zimbabue", continent: "africa", tier: 3, flagFamily: "triangle-star" },
    { code: "zm", name: "Zambia", continent: "africa", tier: 3, flagFamily: "emblem-green" },
    { code: "bw", name: "Botsuana", continent: "africa", tier: 3, flagFamily: "horizontal-blue" },
    { code: "us", name: "Estados Unidos", continent: "north-america", tier: 1, flagFamily: "stars-stripes", aliases: ["eeuu", "usa", "united states"] },
    { code: "ca", name: "Canada", continent: "north-america", tier: 1, flagFamily: "maple-leaf" },
    { code: "mx", name: "Mexico", continent: "north-america", tier: 1, flagFamily: "vertical-tricolor" },
    { code: "gt", name: "Guatemala", continent: "north-america", tier: 2, flagFamily: "vertical-blue-white" },
    { code: "bz", name: "Belice", continent: "north-america", tier: 4, flagFamily: "blue-emblem" },
    { code: "hn", name: "Honduras", continent: "north-america", tier: 3, flagFamily: "horizontal-blue-white" },
    { code: "sv", name: "El Salvador", continent: "north-america", tier: 3, flagFamily: "horizontal-blue-white" },
    { code: "ni", name: "Nicaragua", continent: "north-america", tier: 3, flagFamily: "horizontal-blue-white" },
    { code: "cr", name: "Costa Rica", continent: "north-america", tier: 2, flagFamily: "horizontal-stripes" },
    { code: "pa", name: "Panama", continent: "north-america", tier: 2, flagFamily: "quartered-stars" },
    { code: "cu", name: "Cuba", continent: "north-america", tier: 1, flagFamily: "triangle-star-stripes" },
    { code: "jm", name: "Jamaica", continent: "north-america", tier: 2, flagFamily: "diagonal-cross" },
    { code: "do", name: "Republica Dominicana", continent: "north-america", tier: 2, flagFamily: "cross-emblem" },
    { code: "ht", name: "Haiti", continent: "north-america", tier: 3, flagFamily: "horizontal-emblem" },
    { code: "bs", name: "Bahamas", continent: "north-america", tier: 3, flagFamily: "triangle-stripes" },
    { code: "tt", name: "Trinidad y Tobago", continent: "north-america", tier: 3, flagFamily: "diagonal" },
    { code: "br", name: "Brasil", continent: "south-america", tier: 1, flagFamily: "diamond-emblem", aliases: ["brazil"] },
    { code: "ar", name: "Argentina", continent: "south-america", tier: 1, flagFamily: "horizontal-sun" },
    { code: "cl", name: "Chile", continent: "south-america", tier: 1, flagFamily: "star-canton" },
    { code: "co", name: "Colombia", continent: "south-america", tier: 1, flagFamily: "horizontal-tricolor" },
    { code: "pe", name: "Peru", continent: "south-america", tier: 1, flagFamily: "vertical-red-white" },
    { code: "ve", name: "Venezuela", continent: "south-america", tier: 1, flagFamily: "horizontal-stars" },
    { code: "ec", name: "Ecuador", continent: "south-america", tier: 2, flagFamily: "horizontal-tricolor" },
    { code: "bo", name: "Bolivia", continent: "south-america", tier: 2, flagFamily: "horizontal-tricolor" },
    { code: "py", name: "Paraguay", continent: "south-america", tier: 2, flagFamily: "horizontal-tricolor" },
    { code: "uy", name: "Uruguay", continent: "south-america", tier: 2, flagFamily: "stripes-canton" },
    { code: "gy", name: "Guyana", continent: "south-america", tier: 3, flagFamily: "triangle" },
    { code: "sr", name: "Surinam", continent: "south-america", tier: 3, flagFamily: "horizontal-star" },
    { code: "au", name: "Australia", continent: "oceania", tier: 1, flagFamily: "union-jack-stars" },
    { code: "nz", name: "Nueva Zelanda", continent: "oceania", tier: 1, flagFamily: "union-jack-stars" },
    { code: "pg", name: "Papua Nueva Guinea", continent: "oceania", tier: 2, flagFamily: "diagonal-stars" },
    { code: "fj", name: "Fiyi", continent: "oceania", tier: 3, flagFamily: "union-jack-emblem" },
    { code: "ws", name: "Samoa", continent: "oceania", tier: 3, flagFamily: "star-canton" },
    { code: "to", name: "Tonga", continent: "oceania", tier: 3, flagFamily: "cross-red-white" },
    { code: "vu", name: "Vanuatu", continent: "oceania", tier: 4, flagFamily: "triangle" },
    { code: "sb", name: "Islas Salomon", continent: "oceania", tier: 4, flagFamily: "diagonal-stars" },
    { code: "ki", name: "Kiribati", continent: "oceania", tier: 4, flagFamily: "sun-waves" },
    { code: "ad", name: "Andorra", continent: "europe", tier: 4, flagFamily: "vertical-tricolor" },
    { code: "ba", name: "Bosnia y Herzegovina", continent: "europe", tier: 3, flagFamily: "blue-stars" },
    { code: "by", name: "Bielorrusia", continent: "europe", tier: 3, flagFamily: "horizontal-red-green" },
    { code: "cy", name: "Chipre", continent: "europe", tier: 3, flagFamily: "map-white" },
    { code: "ge", name: "Georgia", continent: "europe", tier: 3, flagFamily: "cross-red-white" },
    { code: "li", name: "Liechtenstein", continent: "europe", tier: 4, flagFamily: "horizontal-bicolor" },
    { code: "lu", name: "Luxemburgo", continent: "europe", tier: 3, flagFamily: "horizontal-tricolor" },
    { code: "mt", name: "Malta", continent: "europe", tier: 3, flagFamily: "vertical-bicolor" },
    { code: "md", name: "Moldavia", continent: "europe", tier: 3, flagFamily: "vertical-tricolor" },
    { code: "mc", name: "Monaco", continent: "europe", tier: 4, flagFamily: "horizontal-red-white" },
    { code: "me", name: "Montenegro", continent: "europe", tier: 3, flagFamily: "emblem-red" },
    { code: "mk", name: "Macedonia del Norte", continent: "europe", tier: 3, flagFamily: "sun-red" },
    { code: "sm", name: "San Marino", continent: "europe", tier: 4, flagFamily: "horizontal-emblem" },
    { code: "va", name: "Ciudad del Vaticano", continent: "europe", tier: 4, flagFamily: "vertical-bicolor" },
    { code: "bh", name: "Barein", continent: "asia", tier: 3, flagFamily: "serrated-red-white" },
    { code: "bt", name: "Butan", continent: "asia", tier: 4, flagFamily: "diagonal-emblem" },
    { code: "bn", name: "Brunei", continent: "asia", tier: 3, flagFamily: "diagonal-emblem" },
    { code: "jo", name: "Jordania", continent: "asia", tier: 2, flagFamily: "pan-arab" },
    { code: "kg", name: "Kirguistan", continent: "asia", tier: 3, flagFamily: "sun-red" },
    { code: "lb", name: "Libano", continent: "asia", tier: 2, flagFamily: "horizontal-emblem" },
    { code: "mv", name: "Maldivas", continent: "asia", tier: 3, flagFamily: "crescent-green" },
    { code: "om", name: "Oman", continent: "asia", tier: 2, flagFamily: "pan-arab" },
    { code: "ps", name: "Palestina", continent: "asia", tier: 2, flagFamily: "pan-arab" },
    { code: "sy", name: "Siria", continent: "asia", tier: 2, flagFamily: "pan-arab" },
    { code: "tj", name: "Tayikistan", continent: "asia", tier: 3, flagFamily: "horizontal-emblem" },
    { code: "tl", name: "Timor Oriental", continent: "asia", tier: 3, flagFamily: "triangle-star" },
    { code: "tm", name: "Turkmenistan", continent: "asia", tier: 3, flagFamily: "vertical-emblem" },
    { code: "tw", name: "Taiwan", continent: "asia", tier: 2, flagFamily: "star-canton" },
    { code: "ye", name: "Yemen", continent: "asia", tier: 2, flagFamily: "pan-arab" },
    { code: "bj", name: "Benin", continent: "africa", tier: 3, flagFamily: "pan-african" },
    { code: "bf", name: "Burkina Faso", continent: "africa", tier: 3, flagFamily: "pan-african" },
    { code: "bi", name: "Burundi", continent: "africa", tier: 3, flagFamily: "diagonal-cross" },
    { code: "cv", name: "Cabo Verde", continent: "africa", tier: 4, flagFamily: "stripes-stars" },
    { code: "cf", name: "Republica Centroafricana", continent: "africa", tier: 3, flagFamily: "horizontal-star" },
    { code: "td", name: "Chad", continent: "africa", tier: 3, flagFamily: "vertical-tricolor" },
    { code: "km", name: "Comoras", continent: "africa", tier: 4, flagFamily: "crescent-stripes" },
    { code: "cg", name: "Republica del Congo", continent: "africa", tier: 3, flagFamily: "diagonal" },
    { code: "dj", name: "Yibuti", continent: "africa", tier: 4, flagFamily: "triangle-star" },
    { code: "er", name: "Eritrea", continent: "africa", tier: 3, flagFamily: "triangle-emblem" },
    { code: "ga", name: "Gabon", continent: "africa", tier: 3, flagFamily: "horizontal-tricolor" },
    { code: "gm", name: "Gambia", continent: "africa", tier: 4, flagFamily: "horizontal-stripes" },
    { code: "gn", name: "Guinea", continent: "africa", tier: 3, flagFamily: "vertical-tricolor" },
    { code: "gw", name: "Guinea-Bisau", continent: "africa", tier: 4, flagFamily: "pan-african" },
    { code: "gq", name: "Guinea Ecuatorial", continent: "africa", tier: 4, flagFamily: "triangle-emblem" },
    { code: "ls", name: "Lesoto", continent: "africa", tier: 4, flagFamily: "horizontal-emblem" },
    { code: "lr", name: "Liberia", continent: "africa", tier: 3, flagFamily: "stars-stripes" },
    { code: "ml", name: "Mali", continent: "africa", tier: 3, flagFamily: "vertical-tricolor" },
    { code: "mr", name: "Mauritania", continent: "africa", tier: 3, flagFamily: "crescent-green" },
    { code: "mu", name: "Mauricio", continent: "africa", tier: 4, flagFamily: "horizontal-stripes" },
    { code: "mw", name: "Malaui", continent: "africa", tier: 3, flagFamily: "horizontal-emblem" },
    { code: "na", name: "Namibia", continent: "africa", tier: 3, flagFamily: "diagonal" },
    { code: "ne", name: "Niger", continent: "africa", tier: 3, flagFamily: "horizontal-circle" },
    { code: "sc", name: "Seychelles", continent: "africa", tier: 4, flagFamily: "diagonal-rays" },
    { code: "sl", name: "Sierra Leona", continent: "africa", tier: 3, flagFamily: "horizontal-tricolor" },
    { code: "so", name: "Somalia", continent: "africa", tier: 3, flagFamily: "star-blue" },
    { code: "ss", name: "Sudan del Sur", continent: "africa", tier: 3, flagFamily: "triangle-star" },
    { code: "st", name: "Santo Tome y Principe", continent: "africa", tier: 4, flagFamily: "triangle-stars" },
    { code: "sz", name: "Esuatini", continent: "africa", tier: 4, flagFamily: "horizontal-emblem" },
    { code: "tg", name: "Togo", continent: "africa", tier: 3, flagFamily: "stripes-canton" },
    { code: "ag", name: "Antigua y Barbuda", continent: "north-america", tier: 4, flagFamily: "triangle-sun" },
    { code: "bb", name: "Barbados", continent: "north-america", tier: 4, flagFamily: "vertical-emblem" },
    { code: "dm", name: "Dominica", continent: "north-america", tier: 4, flagFamily: "cross-emblem" },
    { code: "gd", name: "Granada", continent: "north-america", tier: 4, flagFamily: "border-stars" },
    { code: "kn", name: "San Cristobal y Nieves", continent: "north-america", tier: 4, flagFamily: "diagonal-stars" },
    { code: "lc", name: "Santa Lucia", continent: "north-america", tier: 4, flagFamily: "triangle" },
    { code: "vc", name: "San Vicente y las Granadinas", continent: "north-america", tier: 4, flagFamily: "vertical-emblem" },
    { code: "fm", name: "Micronesia", continent: "oceania", tier: 4, flagFamily: "stars-blue" },
    { code: "mh", name: "Islas Marshall", continent: "oceania", tier: 4, flagFamily: "diagonal-stars" },
    { code: "nr", name: "Nauru", continent: "oceania", tier: 4, flagFamily: "horizontal-star" },
    { code: "pw", name: "Palaos", continent: "oceania", tier: 4, flagFamily: "circle-blue" },
    { code: "tv", name: "Tuvalu", continent: "oceania", tier: 4, flagFamily: "union-jack-stars" },
];
